[package]
name = "json_schema"
version = "0.1.0"
authors = ["Leszek Zalewski <leszekzalewski@fastmail.fm>"]
edition = "2018"

[lib]
name = "json_schema"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.81"
jsonschema = "0.4.3"
serde_json = "1.0"
